# version: "3.8"

# services:
#   nextjs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nextjs-app
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules

version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=https://crm-660080677559.asia-south1.run.app
    volumes:
      - .:/app
      - /app/.next # Persist the Next.js build cache
      - nextjs_node_modules:/app/node_modules
    command: "npm start"

volumes:
  nextjs_node_modules:

